# Generated by Django 5.1.6 on 2025-02-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("library_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="name",
            new_name="AUTHOR",
        ),
        migrations.RemoveField(
            model_name="book",
            name="available_quantity",
        ),
        migrations.RemoveField(
            model_name="book",
            name="book_type",
        ),
        migrations.RemoveField(
            model_name="book",
            name="department",
        ),
        migrations.RemoveField(
            model_name="book",
            name="total_quantity",
        ),
        migrations.AddField(
            model_name="book",
            name="ACC_NUM",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="AMOUNT",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="BOOK_SIZE",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="CALL_NUM",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="COST",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="DATE",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="EDITION",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="INV_DATE",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="INV_NUM",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="PAGES",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="PUBLISHER",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="REMARKS",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="SOURCE",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="TITLE",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="YEAR_PUB",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
